### PR TITLE
Expanded configuration format.

### PR DESCRIPTION
**Pull request by bessdsv**
It is now possible to create a configuration for installing dependencies in different directories.

for example in my project i create next bower.json

```
"install": {
    "path": {
      "jasmine": "tests/libs/jasmine",      
      "all": "src/libs"
    },
    "sources": {
      "jasmine": [
        "bower_components/jasmine/lib/jasmine-core.js"
      ]
    }
  },
  "dependencies": {
    "jasmine": "git://github.com/pivotal/jasmine.git#~2.0.1",
    "backbone-min": "http://backbonejs.org/backbone-min.js",
    "jquery": "1.7.0"
  } 
```

after that backbone-min and jquery were installed in src/libs
and jasmine was installed in tests/libs/jasmine

### CODE REVIEW

**Comment by andrewfan** [comment]
Hey @blittle, will this commit be merged, maybe i can help somehow?

Thanks

**Comment by andrewfan** [comment]
ok, looks like https://github.com/blittle/bower-installer/pull/101 solved this problem

**Comment by drewrawitz** [comment]
Sweet.. thanks @andrewfan for letting us know.  I had no idea about #101.  I've been waiting for this feature for a while :+1:

**Comment by g105b** [comment]
I'm planning on closing this issue. #101 should solve the original problem. If not, please vote here to keep it open and we can look at merging.

**Comment by g105b** [comment]
Closed after 1 week, no votes.

**Pull request closed without merging**
