### PR TITLE
Support for installing to specific path according to file extension and filename

### PR DESCRIPTION
**Pull request by g105b**
This has been implemented to add flexibility to install paths depending on the type of file.
Currently, the install path is solely determined by the path extension. This pull request allows *extension descriptions* to determine the install path.
An extension description is the part of the filename before the final `.`, but coming after a preceeding `.`. For example:
`MyFile.font.css` - the extension is `css`, the extension description is `font.css`, and can be used to further sort large bower projects.

Tests have been written for this new feature. In amongst the PR there are whitespace fixes too, removing trailing tabs on certain lines.

### CODE REVIEW

**Comment by g105b** [comment]
One month later, please can I get some feedback on this PR. I've been using my own fork of bower-installer for projects over the last few weeks, so I would benefit greatly if it was to be merged.

Can you let me know if you have any concerns with the code supplied in the PR? I'll happily work with the code more to ensure it is merged.

**Comment by blittle** [comment]
@g105b I am wondering if this implementation is too specific. I mean the "extension description" is really just part of the file name. It might be more extensible to have the file matcher be a regular expression?

**Comment by g105b** [comment]
I agree with you - that sounds like a more generic approach. May I submit a separate PR for that functionality though, and this one get merged as soon as you can, as I'm using this in projects now and would like to go back to using the main build rather than maintaining my own.

**Comment by g105b** [comment]
@blittle I have implemented the regular expression mapping at #101, closing this PR.

**Comment by blittle** [comment]
Thanks again. For for the delay, been a crazy holiday season...switched jobs :)

**Comment by g105b** [comment]
Hope it's going well for you in your new job. Keep up the good work and thanks for everything. Very happy now 101 is merged.

**Pull request closed without merging**
