### PR TITLE
Readme format all JSON blocks

### PR DESCRIPTION
**Pull request by oscarmorrison**
use 4 space indentation for all blocks (like code style in project)

### CODE REVIEW

**Comment by oscarmorrison** [comment]
@rquadling @blittle

**Comment by oscarmorrison** [comment]
CC @rquadling @blittle

**Comment by blittle** [comment]
Are they not already formatted?

**Comment by oscarmorrison** [comment]
@blittle not properly. there are some spaces after the key, and JSON uses 2space, where as the rest of the code follows 4space styling

**Comment by oscarmorrison** [comment]
@blittle this good to go?

**Pull request merged**
