### PR TITLE
relativeComponentPath from .bowerrc

### PR DESCRIPTION
**Pull request by mculp**
I'm not sure if there's a better way to do this. Since each 'dep' gets prefixed with 'component' in its filename, I am doing a string replace on 'component' from the `directory` key in .bowerrc

Is there a cleaner way to solve this?

Another item of note -- this only affects unspecified sources. For example, since the full component path is already specified for jquery and chosen, only bootstrap will be affected in the config below.

`.bowerrc`
```json
{
  "directory": "vendor/assets/component"
}
```

`bower.json`
```json
{
  "name": "",
  "version": "0.1.0",
  "dependencies": {
    "chosen": "https://github.com/koenpunt/chosen/releases/download/v0.11.1/chosen.zip",
    "jquery-ui": "~> 1.8.0",
    "bootstrap": "~> 2.3.2",
  },
  "install": {
    "path": {
      "js": "vendor/assets/javascripts",
      "css": "vendor/assets/stylesheets",
      "png": "vendor/assets/images"
    },
    "sources" : {
      "chosen": [
        "vendor/assets/components/chosen/chosen.jquery.js",
        "vendor/assets/components/chosen/chosen.css",
        "vendor/assets/components/chosen/chosen-sprite.png",
        "vendor/assets/components/chosen/chosen-sprite@2x.png"
      ],
      "jquery-ui": [
        "vendor/assets/components/jquery-ui/jquery-ui.js",
        "vendor/assets/components/jquery-ui/themes/start/jquery-ui.css",
        "vendor/assets/components/jquery-ui/themes/start/images/ui-bg_flat_55_999999_40x100.png"
      ]
    }
  }
}
```

this solves blittle/bower-installer#38

### CODE REVIEW

**Comment by g105b** [comment]
Going to be looking at merging this when I've got a few moments at the end of this week. Can anyone have a look at the conflicts?

**Comment by chrisjlee** [comment]
I took a quick look at it and this patch needs to be rebased. Everything has been rewritten in `bower-installer.js`

**Comment by g105b** [comment]
Too much has changed in the codebase since the original PR. I'll gladly work on this with you @mculp if you want to spend some time with me to get this issue resolved, but in its current state I am closing as it is not getting attention.

**Comment by zygimantus** [comment]
So does the bower-installer work with "directory" : "any_path_here/bower_components" setting?

**Pull request closed without merging**
